# (PART) From Pittsburgh to Davos {-} 

# The History of EarthTime {#the-history-of-earthtime}

Mapmaking and the use of maps is an ancient idea, it's an impulse we've had for thousands of years. As humans we've been drawing our whereabouts on cave walls since the dawn of our species, but we've come a long way in the last couple hundred years. There's an amazing diversity of the kinds of maps that we're seeing today. There are thousands of satellites that are circling our planet taking a pulse of our planet.

## CMU CREATE LAB

EarthTime evolved from CREATE Lab projects for creating and exploring panoramic imagery, eventually incorporating data sets from such sources

### GigaPan & GigaPan Time Machine

In 2010, the CREATE Lab in collaboration with NASA, developed a technology known as "GigaPan" which captured a mosaic of hundreds or thousands of digital pictures and stitch those frames into a panorama that was able to be explored interactively.

In 2011, released what was known as ["GigaPan Time Machine"](https://www.youtube.com/watch?v=Dk9WanUO_gg), a system that enabled viewers to explore gigapixel-scale, high-resolution videos and image sequences by panning or zooming in and out of the images while simultaneously moving back and forth through time. For examples, were able to use the system to focus in on the details of a booth within a panorama of a carnival midway and also reverse time to see how the booth was constructed; watch a group of plants sprout, grow and flower, but also see others get eaten by caterpillars; or view computer simulations of the early universe, watching as gravity works across 600 million light-years to condense matter into filaments and finally into stars that can be seen by zooming in for a close up. Whereas GigaPan was about exploring physical space at high resolutions, GigaPan Time Machine added the critical element of time to allow viewers to explore both simultaneously. Extending GigaPan into the time dimension, image mosaics were repeatedly captured at set intervals, and then stitched across both space and time to create a video in which each frame was hundreds of millions—and sometimes billions—of pixels.

### Earth-Time Lapse

In 2013 the CREATE Lab began working on its [Explorables Project](https://www.cmucreatelab.org/projects/Explorables), a platform designed to help make big data–with billions of data points, dozens of different fields of information, changing over time–easier to explore, by layering animations over maps with the hope that it would help people make sense of the data by using visual evidence that was more rhetorically compelling that traditional charts or graphs. The Explorables Project also pioneered the use of base maps instead of solely relying on satellite imagery for what would later become EarthTime's alternate basemaps. Early Explorables Project maps opted to leverage the Google Maps API instead with non-satellite data such as statistics on wealth from the World Top Incomes Database.

Of note in 2013, the CREATE Lab in collaboration with Google and TIME Magazine was putting the finishing touches on "Earth-Timelapse", a 52-terapixel time-lapse portrait of Earth that achieved a resolution of 30-meter-per pixel (1.78 trillion pixels per tile) of the planet. This project, led by the CREATE Lab's Randy Sargent and the Earth Engine team, used 909 terabytes of data from a portion of the Landsat satellite corpus (Landsat4, 5, and 7)—with each of the million images coming in at more than 100 megapixels. While Landsat's polar orbit allows its satellites to take a full set of images of the Earth's surface every 16 days, not all those images were usable because of clouds, weather, and other factors. Creating the cloud-free, low-resolution model required 20 terabytes of data from MODIS sensors on NASA's Earth Observing System Terra and Aqua satellites as it had enough differing spectral bands that allowed the team to accurately analyze the atmosphere.

A keen observer of the current version of EarthTime will notice that early years of the dataset—especially 1987—might seem a bit off. This was due to the failure of Landsat 5's Ku-band transmitter which prevented the downlink of imagery collected outside the range of US and cooperating international ground stations. As a result, this meant large chunks of Asia were not covered by Landsat's archives until 1999 and getting a complete picture for each year required interpolation between years where images were available.

The initial data processing to produce the original Earth-Timelapse single shot tiles (from 1984 to 2012) took approximately 260,000 core-hours of CPU time in Google's compute cloud; however, to generate the millions of overlapping video tiles required for Earth-Timelapse's geospatial search capabilities, the CREATE Lab had to leverage Google's computing and storage infrastructure. Encoding of those tiles alone consumed 1.4 million core-hours of compute time and the total process of creating the Earth-Timelapse web application took approximately three days of total processing time and 1.8 million core-hours. At its peak, the project used 66,000 cores simultaneously in Google's cloud. The research with Google done by Sargent and the wider team can be found [here](https://ai.googleblog.com/2013/06/building-visual-planetary-time-machine.html), the subsequent paper on "A Web-based Large-scale Timelapse Editor for Creating and Sharing Guided Video Tours and Interactive Slideshows" by the CREATE Lab can be found [here](https://cmucreatelab.org/files/A%20Web-based%20Large-scale%20Timelapse%20Editor%20for%20Creating%20and%20Sharing%20Guided%20Video%20Tours%20and%20Interactive%20Slideshows.pdf), and the paper from Google on "Google Earth Engine: Planetary-scale geospatial analysis for everyone" can be found [here](https://www.sciencedirect.com/science/article/pii/S0034425717302900?via%3Dihub) for those interested in more details.

### A Wider Reach for the Explorables Project

In 2017, the CREATE Lab released their first visualization of global refugee flows between 2000 - 2015 using data from UNHCR. By 2018, this visual was turned into a series of EarthTime stories for the year's World Refugee Day: ["Global Refugee Crisis: The Big Picture"](https://earthtime.org/stories/global_refugee_crisis_the_big_picture) co-authored with UNHCR and ["Global Refugee Crisis: A System Overburdened"](https://earthtime.org/stories/global_refugee_crisis_a_system_overburdened) co-authored by Dr. Khalid Koser of GCERF.

By late 2017, the Pittsburgh International Airport had installed an EarthTime display in Concourse D as part of its "Creating a Sense of Place" program. Still standing to this day, the display gives travelers a chance to interact with the CREATE Lab's technology and see how research conducted at Carnegie Mellon University is shaping the future of the world.

## World Economic Forum Partnership

### Global Situation Space

### Strategic Intelligence

### Agenda Blogs

## EarthTime Today

The tool is immediately recognized around the world by its stunning “Annual Timelapse” base layer is a 35-year annual record of the Earth's change viewed from space. To date, the platform has incorporated massive archive of data from eight satellites, including USGS's Landsat series, NASA's Terra and Aqua, and ESA's Sentinel 2 series, and continues to combine that data into annual atmospherically corrected and cloud-removed mosaics tiles. It now also includes a special data layer from Himawari 8, the geostationary weather satellite, operated by Japan Meteorological Agency.

In late 2017, the Pittsburgh International Airport had installed an EarthTime display in Concourse D as part of its "Creating a Sense of Place" program. Still standing to this day, the display gives travelers a chance to interact with the CREATE Lab's technology and see how research conducted at Carnegie Mellon University is shaping the future of the world.

Apart from the World Economic Forum’s Annual Meetings, EarthTime has also been used by countless researchers, US congressional sub-committee hearings, COP14 in Sharm el-Sheikh, the TED Conference, the Prince Albert II of Monaco Foundation at the Monaco Yacht Club, the Arctic Circle Assembly in Reykjavik, as a teaching tool in classrooms teachers, by community organizations and advocacy groups,  as well as journalists helping to broaden the scope of their stories both locally and globally. 

EarthTime continues to be underpinned by the CREATE Lab's vision to promote data literacy, inspire meaningful dialogue, and democratize access to data for everyone in an inclusive and transparent way.
