# (PART) Inspiring Meaningful Dialogue {-} 

# Closing Remarks

If you’ve reached the end of this document, hopefully you see that EarthTime is comprehensive and powerful tool for communicating data in a way that resonates with people across the world. The developments pioneered at the CREATE Lab—mainly storing information and using graphic processes in computers to make this possible and on being very smart with using internet bandwidth cleverly—has drastically changed our relationship with data. Fundamentally, the fact that we can take now any dataset and explore it through space and time reveals to us the possibility of thinking about data very differently than we did even ten years ago where we had to put the same data in a table and look at trends overtime. The reason this is interesting is because people who have traditionally looked at quantitative data analytically using tools like MatLab or Excel can now visually understand the data more immediately than ever before. In the case of EarthTime, with its billions of pixels of data being provided to the human body, it has shown time and again that the most efficient technique we have for understanding data is our eyes. After finishing this document, you’ll now be able to take almost any dataset and create quantitative information from it that can be visually intimate to your audience, which helps create a new revolution in helping us understand the Earth itself. This gives us the ability to change the relationship we have with the data because we can ask the questions we couldn’t have asked before and visualize them.

While EarthTime by itself is effective in communicating data and visualizing data in a way that is more easily digestible to a wider audience. We’ve found that what turns it from an effective tool into affective one, is when the tool is combined with powerful narratives coming from someone who is a content expert in the area and represents the best possible way of thinking about the data. This also protects the providence and trust that we’ve garnered with EarthTime over the years. Remember that it is the experts who can ultimately guide the viewer how to think about the data in a way where one starts to understand some of the underlying causes without overthinking some of the correlations that they might be seeing visually. In doing so, EarthTime tries to influence the downstream understanding of the data as much as possible because those who work closely with the tool recognize that there is no substitute for guidance by remarkable individuals.

There've been numerous cases of audiences viewing an EarthTime story and when an expert explains how to think about the data, the audience starts to develop a new eye for the data. This helps to create a miniature expert eye, so then when the audience encounters the data later, they usually do a better job at understanding it. Looking at today’s tsunami of data without guidance from an expert narrative is a disaster. People don’t know where to start and we often liken it to drinking from a fire hydrant. But once they start using EarthTime, they start to develop a mental model for how to use the data and think about the data.

We hope this document has allowed you to develop a mental model for how to use EarthTime and think about how to use the tool in various scenarios. Please remember to enjoy the full EarthTime process and we hope that you're now more confident in your ability to create powerful stories that can help shed light on some of the most pressing issues of our time.